// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/accessapproval/v1/accessapproval.proto

package com.google.cloud.accessapproval.v1;

public interface ApproveDecisionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.accessapproval.v1.ApproveDecision)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The time at which approval was granted.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp approve_time = 1;</code>
   * @return Whether the approveTime field is set.
   */
  boolean hasApproveTime();
  /**
   * <pre>
   * The time at which approval was granted.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp approve_time = 1;</code>
   * @return The approveTime.
   */
  com.google.protobuf.Timestamp getApproveTime();
  /**
   * <pre>
   * The time at which approval was granted.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp approve_time = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getApproveTimeOrBuilder();

  /**
   * <pre>
   * The time at which the approval expires.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expire_time = 2;</code>
   * @return Whether the expireTime field is set.
   */
  boolean hasExpireTime();
  /**
   * <pre>
   * The time at which the approval expires.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expire_time = 2;</code>
   * @return The expireTime.
   */
  com.google.protobuf.Timestamp getExpireTime();
  /**
   * <pre>
   * The time at which the approval expires.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expire_time = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpireTimeOrBuilder();
}
