// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/accessapproval/v1/accessapproval.proto

package com.google.cloud.accessapproval.v1;

public interface DismissDecisionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.accessapproval.v1.DismissDecision)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The time at which the approval request was dismissed.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dismiss_time = 1;</code>
   * @return Whether the dismissTime field is set.
   */
  boolean hasDismissTime();
  /**
   * <pre>
   * The time at which the approval request was dismissed.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dismiss_time = 1;</code>
   * @return The dismissTime.
   */
  com.google.protobuf.Timestamp getDismissTime();
  /**
   * <pre>
   * The time at which the approval request was dismissed.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dismiss_time = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDismissTimeOrBuilder();
}
