// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/accessapproval/v1/accessapproval.proto

package com.google.cloud.accessapproval.v1;

public interface EnrolledServiceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.accessapproval.v1.EnrolledService)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The product for which Access Approval will be enrolled. Allowed values are
   * listed below (case-sensitive):
   * - all
   * - appengine.googleapis.com
   * - bigquery.googleapis.com
   * - bigtable.googleapis.com
   * - cloudkms.googleapis.com
   * - compute.googleapis.com
   * - dataflow.googleapis.com
   * - iam.googleapis.com
   * - pubsub.googleapis.com
   * - storage.googleapis.com
   * </pre>
   *
   * <code>string cloud_product = 1;</code>
   * @return The cloudProduct.
   */
  java.lang.String getCloudProduct();
  /**
   * <pre>
   * The product for which Access Approval will be enrolled. Allowed values are
   * listed below (case-sensitive):
   * - all
   * - appengine.googleapis.com
   * - bigquery.googleapis.com
   * - bigtable.googleapis.com
   * - cloudkms.googleapis.com
   * - compute.googleapis.com
   * - dataflow.googleapis.com
   * - iam.googleapis.com
   * - pubsub.googleapis.com
   * - storage.googleapis.com
   * </pre>
   *
   * <code>string cloud_product = 1;</code>
   * @return The bytes for cloudProduct.
   */
  com.google.protobuf.ByteString
      getCloudProductBytes();

  /**
   * <pre>
   * The enrollment level of the service.
   * </pre>
   *
   * <code>.google.cloud.accessapproval.v1.EnrollmentLevel enrollment_level = 2;</code>
   * @return The enum numeric value on the wire for enrollmentLevel.
   */
  int getEnrollmentLevelValue();
  /**
   * <pre>
   * The enrollment level of the service.
   * </pre>
   *
   * <code>.google.cloud.accessapproval.v1.EnrollmentLevel enrollment_level = 2;</code>
   * @return The enrollmentLevel.
   */
  com.google.cloud.accessapproval.v1.EnrollmentLevel getEnrollmentLevel();
}
